from django import forms
from .models import UserProfile

# List of top 80 coding languages
CODING_LANGUAGES = [
    ('Python', 'Python'),
    ('JavaScript', 'JavaScript'),
    ('Java', 'Java'),
    ('C#', 'C#'),
    ('C++', 'C++'),
    ('Ruby', 'Ruby'),
    ('PHP', 'PHP'),
    ('Swift', 'Swift'),
    ('Go', 'Go'),
    ('TypeScript', 'TypeScript'),
    ('HTML', 'HTML'),
    ('CSS', 'CSS'),
    ('SQL', 'SQL'),
    ('R', 'R'),
    ('Kotlin', 'Kotlin'),
    ('Scala', 'Scala'),
    ('Perl', 'Perl'),
    ('Haskell', 'Haskell'),
    ('Lua', 'Lua'),
    ('Rust', 'Rust'),
    ('MATLAB', 'MATLAB'),
    ('Objective-C', 'Objective-C'),
    ('Groovy', 'Groovy'),
    ('Dart', 'Dart'),
    ('Clojure', 'Clojure'),
    ('Julia', 'Julia'),
    ('Solidity', 'Solidity'),
    ('Shell', 'Shell'),
    ('Tcl', 'Tcl'),
    ('Scheme', 'Scheme'),
    ('VHDL', 'VHDL'),
    ('ActionScript', 'ActionScript'),
    ('Smalltalk', 'Smalltalk'),
    ('Ada', 'Ada'),
    ('Racket', 'Racket'),
    ('Elixir', 'Elixir'),
    ('COBOL', 'COBOL'),
    ('Forth', 'Forth'),
    ('Verilog', 'Verilog'),
    ('Eiffel', 'Eiffel'),
    ('APL', 'APL'),
    ('SML', 'SML'),
    ('D', 'D'),
    ('Objective-Caml', 'Objective-Caml'),
    ('AWK', 'AWK'),
    ('Erlang', 'Erlang'),
    ('Modula-2', 'Modula-2'),
    ('XSL', 'XSL'),
    ('XSLT', 'XSLT'),
    ('Lisp', 'Lisp'),
    ('OpenCOBOL', 'OpenCOBOL'),
    ('XQuery', 'XQuery'),
    ('SDL', 'SDL'),
    ('IDL', 'IDL'),
    ('RPG', 'RPG'),
    ('Ch', 'Ch'),
    ('Nim', 'Nim'),
    ('PL/SQL', 'PL/SQL'),
    ('Verilog', 'Verilog'),
    ('Starlark', 'Starlark'),
    ('ML', 'ML'),
    ('Zsh', 'Zsh'),
    ('Pike', 'Pike'),
    ('Sh', 'Sh'),
    ('Tcl', 'Tcl'),
    ('SystemVerilog', 'SystemVerilog'),
    ('Fortran', 'Fortran'),
    ('Prolog', 'Prolog'),
    ('Mercury', 'Mercury'),
    ('PostScript', 'PostScript'),
    ('F#', 'F#'),
    ('OCaml', 'OCaml'),
    ('Q', 'Q'),
    ('Oz', 'Oz'),
    ('Icon', 'Icon'),
    ('Vim Script', 'Vim Script'),
    ('AutoIt', 'AutoIt'),
    ('Turing', 'Turing'),
    ('Zig', 'Zig'),
    ('J', 'J'),
    ('Crystal', 'Crystal'),
    ('V', 'V'),
    ('Rebol', 'Rebol'),
    ('Red', 'Red'),
    ('Nix', 'Nix'),
    ('Assembly', 'Assembly'),
    ('Ada', 'Ada'),
    ('Nim', 'Nim'),
    ('ALGOL', 'ALGOL'),
    ('Bash', 'Bash'),
    ('Sed', 'Sed'),
    ('Batch', 'Batch'),
    ('ColdFusion', 'ColdFusion'),
    ('Euphoria', 'Euphoria'),
    ('GAMS', 'GAMS'),
    ('Genie', 'Genie'),
    ('IDL', 'IDL'),
    ('Io', 'Io'),
    ('J#', 'J#'),
    ('JScript', 'JScript'),
    ('KornShell', 'KornShell'),
    ('LiveScript', 'LiveScript'),
    ('M4', 'M4'),
    ('MUMPS', 'MUMPS'),
    ('OCaml', 'OCaml'),
    ('Occam', 'Occam'),
    ('Opa', 'Opa'),
    ('Pascal', 'Pascal'),
    ('PowerShell', 'PowerShell'),
    ('Puppet', 'Puppet'),
    ('QBasic', 'QBasic'),
    ('REXX', 'REXX'),
    ('Ring', 'Ring'),
    ('RPG IV', 'RPG IV'),
    ('SAS', 'SAS'),
    ('SPARK', 'SPARK'),
    ('Squirrel', 'Squirrel'),
    ('SuperCollider', 'SuperCollider'),
    ('Turing', 'Turing'),
    ('VBScript', 'VBScript'),
    ('Wolfram', 'Wolfram'),
    ('Xojo', 'Xojo'),
    ('YAML', 'YAML'),
    ('Nemerle', 'Nemerle'),
    ('Fantom', 'Fantom'),
    ('PureScript', 'PureScript'),
    ('Bosque', 'Bosque'),
    ('LabVIEW', 'LabVIEW'),
    ('Lisp', 'Lisp'),
    ('Objective-Caml', 'Objective-Caml'),
    ('Zig', 'Zig'),
    ('Assembly', 'Assembly'),
    ('F#', 'F#'),
    ('Zig', 'Zig'),
    ('UnrealScript', 'UnrealScript'),
    ('Crystal', 'Crystal'),
    ('Loom', 'Loom'),
    ('Simula', 'Simula'),
    ('Nim', 'Nim'),
    ('Mercury', 'Mercury'),
    ('Haxe', 'Haxe'),
    ('SML', 'SML'),
    ('Eiffel', 'Eiffel'),
    ('VHDL', 'VHDL'),
    ('Fortran', 'Fortran'),
    ('Pascal', 'Pascal'),
    ('Ballerina', 'Ballerina'),
    ('Turing', 'Turing'),
    ('Pike', 'Pike'),
    ('Vala', 'Vala'),
    ('AutoHotkey', 'AutoHotkey'),
    ('Oberon', 'Oberon'),
    ('Idris', 'Idris'),
    ('Smalltalk', 'Smalltalk'),
    ('Bosque', 'Bosque'),
    ('Vim', 'Vim'),
    ('Zig', 'Zig'),
    ('Eff', 'Eff'),
    ('ReScript', 'ReScript'),
    ('J', 'J'),
    ('Q', 'Q'),
    ('Bosque', 'Bosque'),
    ('Cobra', 'Cobra'),
    ('SuperCollider', 'SuperCollider'),
    ('Modula-2', 'Modula-2'),
    ('Starlark', 'Starlark'),
    ('AutoIt', 'AutoIt'),
    ('Scratch', 'Scratch'),
    ('Eff', 'Eff'),
    ('Genie', 'Genie'),
    ('Newspeak', 'Newspeak'),
    ('Prolog', 'Prolog'),
    ('Vala', 'Vala'),
    ('Pep', 'Pep'),
    ('Nemerle', 'Nemerle'),
    ('J#', 'J#'),
    ('Hack', 'Hack'),
    ('XSLT', 'XSLT'),
    ('Gosu', 'Gosu'),
    ('XSL', 'XSL'),
    ('Tcl', 'Tcl'),
    ('Tcl', 'Tcl'),
    ('Dhall', 'Dhall'),
    ('Turing', 'Turing'),
    ('X++', 'X++'),
    ('Zig', 'Zig'),
    ('QML', 'QML'),
    ('Verilog', 'Verilog'),
    ('Nim', 'Nim'),
    ('Io', 'Io'),
    ('JScript', 'JScript'),
    ('Modula-2', 'Modula-2'),
    ('SPARQL', 'SPARQL'),
    ('E', 'E'),
    ('QBasic', 'QBasic'),
    ('Puppet', 'Puppet'),
    ('Nim', 'Nim'),
    ('Forth', 'Forth'),
    ('Haskell', 'Haskell'),
    ('Ring', 'Ring'),
    ('YAML', 'YAML'),
    ('Crystal', 'Crystal'),
    ('Forth', 'Forth'),
    ('Rust', 'Rust'),
    ('Zig', 'Zig'),
    ('Turing', 'Turing'),
    ('S', 'S'),
    ('Assembly', 'Assembly'),
    ('Sh', 'Sh'),
    ('OCaml', 'OCaml'),
    ('Squirrel', 'Squirrel'),
    ('Io', 'Io'),
    ('Gherkin', 'Gherkin'),
    ('XQuery', 'XQuery'),
    ('V', 'V'),
    ('Crystal', 'Crystal'),
    ('R', 'R'),
    ('J#', 'J#'),
    ('Bosque', 'Bosque'),
    ('Icon', 'Icon'),
    ('D', 'D'),
    ('SML', 'SML'),
    ('Opa', 'Opa'),
    ('Pep', 'Pep'),
    ('Scala', 'Scala'),
    ('LiveScript', 'LiveScript'),
    ('Io', 'Io'),
    ('SuperCollider', 'SuperCollider'),
    ('JScript', 'JScript'),
    ('Crystal', 'Crystal'),
    ('XSL', 'XSL'),
    ('Sed', 'Sed'),
    ('Turing', 'Turing'),
    ('Idris', 'Idris'),
    ('Simula', 'Simula'),
    ('Turing', 'Turing'),
    ('Haxe', 'Haxe'),
    ('Groovy', 'Groovy'),
    ('Racket', 'Racket'),
    ('LabVIEW', 'LabVIEW'),
    ('Fortran', 'Fortran'),
    ('Racket', 'Racket'),
    ('Forth', 'Forth'),
    ('Pascal', 'Pascal'),
    ('Fantom', 'Fantom'),
    ('Zig', 'Zig'),
    ('Bosque', 'Bosque'),
    ('V', 'V'),
    ('Sh', 'Sh'),
    ('SuperCollider', 'SuperCollider'),
    ('Pep', 'Pep'),
    ('E', 'E'),
    ('Bosque', 'Bosque'),
    ('QML', 'QML'),
    ('Assembly', 'Assembly'),
    ('Crystal', 'Crystal'),
    ('Turing', 'Turing'),
    ('Dart', 'Dart'),
    ('Bosque', 'Bosque'),
    ('Newspeak', 'Newspeak'),
    ('SML', 'SML'),
    ('Zig', 'Zig'),
    ('Hack', 'Hack'),
    ('Tcl', 'Tcl'),
    ('Nim', 'Nim'),
    ('Io', 'Io'),
    ('Racket', 'Racket'),
    ('Sh', 'Sh'),
    ('V', 'V'),
    ('J', 'J'),
]


class AdditionalInfoForm(forms.Form):
    coding_languages = forms.ChoiceField(
        label='Coding Languages',
        choices=CODING_LANGUAGES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    tech_career_interest = forms.CharField(
        label='Tech Career Interest',
        widget=forms.Textarea(attrs={'rows': 3, 'class': 'form-control'})
    )
    email = forms.EmailField(
        label='Email Address',
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

class EditProfileForm(forms.ModelForm):
    coding_languages = forms.ChoiceField(
        label='Coding Languages',
        choices=CODING_LANGUAGES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    tech_career_interest = forms.CharField(
        label='Tech Career Interest',
        widget=forms.Textarea(attrs={'rows': 3, 'class': 'form-control'})
    )

    class Meta:
        model = UserProfile
        fields = ['coding_languages', 'tech_career_interest']
